In [53]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [54]:
data = pd.read_csv('emails.csv')

In [55]:
data.head(10)

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1
5  Subject: great nnews  hello , welcome to medzo...     1
6  Subject: here ' s a hot play in motion  homela...     1
7  Subject: save your money buy getting this thin...     1
8  Subject: undeliverable : home based business f...     1
9  Subject: save your money buy getting this thin...     1

In [56]:
data['spam'].value_counts()

spam
0    4360
1    1368
Name: count, dtype: int64

In [57]:
data.isnull().sum()

text    0
spam    0
dtype: int64

In [58]:
data.drop_duplicates(inplace=True)

In [59]:
data['spam'].value_counts()

spam
0    4327
1    1368
Name: count, dtype: int64

In [60]:
x = data['text'].values
y = data['spam'].values

In [61]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [62]:
from sklearn.feature_extraction.text import CountVectorizer

In [63]:
cv = CountVectorizer()

In [64]:
X_train = cv.fit_transform(x_train)
X_test = cv.transform(x_test)

In [65]:
X_train.toarray()

array([[0, 3, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [66]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [67]:
from sklearn.naive_bayes import MultinomialNB

In [68]:
nb = MultinomialNB()

In [69]:
nb.fit(X_train,y_train)

MultinomialNB()

In [70]:
nb.score(X_test,y_test)

0.9936797752808989

In [71]:
emails = ['Congratulation,Nabib! You got 10 thousand dollar in this term']

In [72]:
cv_emails = cv.transform(emails)

In [73]:
nb.predict(cv_emails)

array([1], dtype=int64)